image: mhart/alpine-node:8

stages:
  - install&build
  - deploy

install&build:
  stage: install&build
  script:
    - npm install
    - npm run build:app
  artifacts:
    paths:
      - public

pages:
  stage: deploy
  script:
  - echo 'Nothing to do...'
  artifacts:
    paths:
      - public
  dependencies:
    - install&build
  only:
  - master

api:
  image: ruby:latest
  stage: deploy
  before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
  only: 
  - master
