name: CI

on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache NPM
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install
        run: npm ci

  test-app: 
    needs: [install]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache NPM
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install
        run: npm ci
      - name: Install Playwright
        run: npm run e2e:install
      - name: Test App
        run: |
          npm run app &
          npm run e2e
        timeout-minutes: 5

  build-app:
    env:
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
    needs: [install, test-app]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache NPM
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install
        run: npm ci
      - name: Build App
        run: npm run build:app
        timeout-minutes: 5
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy App
        run: |
          cd public/
          zip -r build.zip .
          aws s3 cp build.zip s3://tic-metac-toe/${{ github.sha }}.zip --content-type "application/zip; charset=utf-8"
          URL=$(aws s3 presign s3://tic-metac-toe/${{ github.sha }}.zip)
          aws amplify start-deployment --app-id ${{ secrets.AWS_AMPLIFY_APP_ID }} --branch-name prod --source-url $URL

  build-api:
    needs: [install, test-app]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy to Heroku
        run: git push https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git main
